version: '3'

volumes:
  data1:
  data2:

services:

  postgres-internal:
    container_name: prontuario-java-batch-postgres-internal
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internal-prontuariodb
    ports:
      - 5432:5432
    volumes:
      - data1:/var/lib/postgresql
    networks:
      - global-default

  postgres-external:
    container_name: prontuario-java-batch-postgres-external
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: external-prontuariodb
    ports:
      - 5433:5432
    volumes:
      - data2:/var/lib/postgresql
      - ./src/main/resources/db/migration/external/criarTabelasProntuario.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - global-default

  localstack:
    container_name: prontuario-java-batch-localstack
    image: localstack/localstack
    networks:
      - global-default
    ports:
      - '4566:4566'
    volumes:
      - ./aws/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    environment:
      - SERVICES=s3,sqs,secretsmanager
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key

networks:
  global-default:
    external: true