version: '3'

volumes:
  data:

services:

  postgres:
    container_name: prontuario-java-batch-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prontuariodb
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - global-default

  localstack:
    container_name: prontuario-java-batch-localstack
    image: localstack/localstack
    networks:
      - global-default
    ports:
      - '4566:4566'
    volumes:
      - ./aws/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    environment:
      - SERVICES=s3,sqs,secretsmanager
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key

networks:
  global-default:
    external: true